name: build-remotely
run-name: ${{ github.actor }} triggered a remote build
on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://build.zhufucdev.com/job/Motion%20Emulator/build?token=${{ secrets.JENKINS_TOKEN }}'
          method: 'GET'